name: Deploy Node.js + React App to Azure

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install and Build React App
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Move React Build to Backend
        run: |
          rm -rf backend/build
          cp -r frontend/build backend/build

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: '4locospadel'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend