name: Deploy Node/React App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install Project Dependencies
        run: npm install

      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm cache clean --force
          npm install
          npm run build

      - name: Replace Build Folder
        run: |
          rm -rf ./backend/build
          cp -r ./frontend/build ./backend/build

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm cache clean --force
          npm install

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 4locospadel
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}